"""add aux token columns to messages (Fase 9.8 A10)

Revision ID: 325c4ee3c6cf
Revises: 3feae8cc3c61
Create Date: 2026-09-11 14:55:07.216206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325c4ee3c6cf'
down_revision: Union[str, Sequence[str], None] = '3feae8cc3c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('aux_prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('aux_completion_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'aux_completion_tokens')
    op.drop_column('messages', 'aux_prompt_tokens')
    # ### end Alembic commands ###
