"""db integrity audit: unique/check constraints, chunks indexes

Revision ID: 80e54d617458
Revises: cf62d1f2007f
Create Date: 2026-08-06 09:54:33.131220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e54d617458'
down_revision: Union[str, Sequence[str], None] = 'cf62d1f2007f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_embedding_hnsw_cosine', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_unique_constraint('uq_conversations_platform_chat_id', 'conversations', ['platform', 'chat_id'])
    # ### end Alembic commands ###

    # Los CheckConstraint de los modelos NO los detecta --autogenerate
    # (limitacion conocida de Alembic para constraints a nivel de tabla) --
    # se agregan a mano aca. Todos verificados contra la DB real antes de
    # escribir esta migracion (auditoria de base de datos, 2026-08-06): cero
    # filas violan ninguno de estos dominios hoy.
    op.create_check_constraint(
        "ck_conversations_platform", "conversations", "platform IN ('telegram', 'whatsapp', 'web')"
    )
    op.create_check_constraint("ck_messages_role", "messages", "role IN ('user', 'assistant')")
    op.create_check_constraint("ck_feedback_rating", "feedback", "rating IN ('util', 'no_util')")
    op.create_check_constraint(
        "ck_ingestion_logs_status", "ingestion_logs", "status IN ('running', 'success', 'failed')"
    )
    op.create_check_constraint(
        "ck_legal_relations_relation_type", "legal_relations", "relation_type IN ('deroga', 'reforma', 'adiciona')"
    )
    op.create_check_constraint(
        "ck_legal_relations_extraction_method",
        "legal_relations",
        "extraction_method IN ('regex', 'regex_publicada', 'regex_se_verbo')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_legal_relations_extraction_method", "legal_relations", type_="check")
    op.drop_constraint("ck_legal_relations_relation_type", "legal_relations", type_="check")
    op.drop_constraint("ck_ingestion_logs_status", "ingestion_logs", type_="check")
    op.drop_constraint("ck_feedback_rating", "feedback", type_="check")
    op.drop_constraint("ck_messages_role", "messages", type_="check")
    op.drop_constraint("ck_conversations_platform", "conversations", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_conversations_platform_chat_id', 'conversations', type_='unique')
    op.drop_index('ix_chunks_embedding_hnsw_cosine', table_name='chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    # ### end Alembic commands ###
