"""baseline schema real

Revision ID: cf62d1f2007f
Revises:
Create Date: 2026-07-25 17:32:00.206599

This is a BASELINE revision, not a real migration. Before this revision,
LexChiapas had no Alembic history: every table/column in the real DB
(documents, chunks, conversations, messages, feedback, ingestion_logs,
semantic_cache, legal_relations, golden_dataset_runs,
golden_dataset_run_cases -- including columns added later by hand such as
messages.jailbreak_detected, messages.was_rewritten,
messages.search_time_ms/generation_time_ms, messages.agent_trace) was
created by manual ALTER TABLE / CREATE TABLE statements with no script in
git.

`alembic revision --autogenerate` against the real DB produced an EMPTY
diff (upgrade/downgrade below are both `pass`) -- confirming the
SQLAlchemy models in app/models/ already match the real schema exactly, so
there is nothing to create here. This revision exists only so
`alembic stamp head` can mark the real DB as being at this point in
history. Do NOT run `alembic upgrade head` starting from this revision
against an empty database -- it will not create any tables.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf62d1f2007f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
